#!/usr/bin/env bash
#
# Copyright (c) 2019 by lulongij of lu.
# All rights reserved.
#
#ident  "@(#)docker 1.0"

#更新yum
sudo yum -y update
#更新缓存
sudo yum makecache fast

#设置仓库
sudo yum install -y yum-utils  device-mapper-persistent-data lvm2
sudo yum-config-manager  --add-repo  https://download.docker.com/linux/centos/docker-ce.repo

#安装 Docker Engine-Community
sudo yum install docker-ce docker-ce-cli containerd.io

#查看docker版本
sudo docker --version




