#!/usr/bin/env bash
#
# Copyright (c) 2019 by lulongij of lu.
# All rights reserved.
#
#ident  "@(#)docker 1.0"


# centos7
# 设置开机启动
sudo systemctl enable docker

# 启动docker服务
sudo systemctl start docker

# 添加docker用户组、免sudo调用
sudo groupadd docker

# 添加当前用户到 docker 组
sudo usermod -aG docker ${USER}

# 重启docker
sudo systemctl daemon-reload
sudo systemctl restart docker

# 生效配置
newgrp - docker

# 查看docker版本
docker --version



